### ISSUE TITLE
Maximum upload size exceeded when uploading DAM files

### ISSUE THREAD

**Issue by epetersen-sci** [orijitghosh/VANESSA-DAM#3]
Many of our DAM files are quite large. Since this is running locally for me, could the size limit be removed, or at least put high enough that this shouldn't be an issue (maybe ~100 MB?)

**Comment by orijitghosh** [comment]
Hi @epetersen-sci , I was on vacation, so could not reply to you sooner. I have not implemented any file size limit, but by default, shiny limits it to 5MB. Since you are running locally, would you mind putting this line at the top of the `server.r` file: `options(shiny.maxRequestSize = 100 * 1024^2)` (for increasing the limit to 100MB), and then running the apps? I will make sure to add this next time I update the apps.
